# Generated by Django 4.1.5 on 2023-01-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroImg', models.ImageField(upload_to='media/resume/')),
                ('intro', models.CharField(max_length=250)),
                ('skill1', models.TextField(max_length=1000)),
                ('skill2', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/about/')),
                ('home', models.TextField(max_length=1000)),
                ('about', models.TextField(max_length=1000)),
                ('portfolio', models.TextField(max_length=1000)),
                ('blog', models.TextField(max_length=1000)),
                ('dropdown', models.TextField(blank=True, max_length=1000, null=True)),
                ('contact', models.TextField(max_length=1000)),
            ],
        ),
    ]
