# Generated by Django 4.1.5 on 2023-01-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='Title',
            new_name='title',
        ),
    ]
