# Generated by Django 4.1.5 on 2023-01-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='media/resume/')),
                ('level', models.CharField(max_length=250)),
                ('passed_year', models.CharField(max_length=200)),
                ('discription', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='media/resume/')),
                ('skill_name', models.CharField(max_length=250)),
                ('about_skill', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WorkedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='media/resume/')),
                ('company_name', models.CharField(max_length=250)),
                ('about_work', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_currently_working_here', models.BooleanField(default=False)),
            ],
        ),
    ]
